# Generated by Django 4.2.11 on 2024-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='apellido')),
                ('age', models.PositiveSmallIntegerField(verbose_name='edad')),
            ],
        ),
    ]
