# Generated by Django 4.2.11 on 2024-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
