# Generated by Django 4.2.11 on 2024-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_rename_name_autor_nombre_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
